package songPackage;

public class Assignment {}
/*
Write a script to apply the right form of cryptoanalysis 
able to disclose the plaintext of the text below. 
Hint: it's the lyrics of a song.



FCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKF

CGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFC

GUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCG

UNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGU

NKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUN

KBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNK

BHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKB

HEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBH

EJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHEJGCLKFCGUNKBHE

JGCLKFCGUNKBHEJGCLK

Notes: The "lyric" is just "FCGUNKBHEJGCLK" repeating over and over.
14 letters
repeats 38 times

Cesear Cipher - no
Affine Cipher - untested
Double Transcription - untested
One-Time Pad - no
*/
